version: "3.8"

services:
  client-react:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
