version: "3.8"

services:
  client-react:
    container_name: client_React
    restart: unless-stopped
    env_file:
      - .env
    image: client:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    networks:
      - shared-network

networks:
  shared-network:
    external: true
